---
dist: jammy
language: python
python:
  - "3.11"
env:
  - SETUP_TARGET=.

# before_script:
#   - pip install $SETUP_TARGET
script:
  - >-
    echo -e "${ANSI_GREEN}Running pre-commit...${ANSI_RESET}"
    && echo -en 'travis_fold:start:precommit\\r'
  - pre-commit run -a
  - echo -en 'travis_fold:end:precommit\\r'
  # - >-
  #   echo -e "${ANSI_GREEN}Running Tests...${ANSI_RESET}"
  #   && echo -en 'travis_fold:start:tests\\r'
  # - python -m unittest discover
  # - echo -en 'travis_fold:end:tests\\r'
