benchmark: fever
budget: null
budget_growth: double
demonstrations_variable_name: demonstrations
initial_test_set_size: 1
max_test_set_size: 1000
num_candidates: 6
num_demonstrations: 5
parallelism: 1
shuffle_test: false
test_set_name: test
timeout: 120
train_set_name: train
variables:
  model:
  - ibm/granite-20b-multilingual
  prompt_pattern:
  - cot
  - react
  - rewoo

# "model": self.sample_random_index(
#     [
#         # "ibm/granite-13b-instruct-v2",
#         # "ibm/granite-13b-chat-v2",
#         # "meta-llama/llama-3-1-70b-instruct",
#         # "meta-llama/llama-3-405b-instruct",
#         "ibm/granite-20b-multilingual",
#         # "ibm/granite-20b-multilang-lab-rc",
#         # "ibm/granite-7b-lab",
#         # "meta-llama/llama-3-70b-instruct"
#         # str(Models.granite_34b_code_instruct),
#     ],
# ),