benchmark: evalplus
budget: null
budget_growth: double
demonstrations_variable_name: demonstrations
initial_test_set_size: 1
max_test_set_size: 1000
num_candidates: 1
num_demonstrations: 5
parallelism: 1
shuffle_test: false
test_set_name: test
timeout: 120
train_set_name: train
variables:
  model:
  - ibm/granite-34b-code-instruct
  prompt_pattern:
  - cot
