/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PDLSchemas = Program | PdlBlock
/**
 * Prompt Declaration Language program (PDL)
 */
export type Program =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Documentation associated to the block.
 *
 */
export type Description = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description1 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description2 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description3 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description4 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description5 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description6 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description7 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description8 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description9 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description10 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description11 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description12 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description13 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description14 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description15 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description16 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description17 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description18 = string | null
/**
 * Documentation associated to the block.
 *
 */
export type Description19 = string | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def = string | null
export type ContributeTarget = "result" | "context"
export type Value = unknown[]
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
export type Description20 = string | null
export type Spec20 = {
  [k: string]: unknown
} | null
export type Pdl =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
export type Description21 = string | null
export type Spec21 = {
  [k: string]: unknown
} | null
export type Regex = string
export type Mode = "search" | "match" | "fullmatch" | "split" | "findall"
/**
 * Block to execute in case of error.
 *
 */
export type Fallback =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role = string | null
/**
 * Current context
 *
 */
export type Context =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId = string | null
export type Path = string[]
export type File = string
export type StartNanos = number | null
export type EndNanos = number | null
export type FirstUseNanos = number | null
export type Timezone = string | null
export type Kind = "empty"
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def1 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute1 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser1 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback1 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role1 = string | null
/**
 * Current context
 *
 */
export type Context1 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId1 = string | null
export type Kind1 = "error"
/**
 * Error message.
 *
 */
export type Msg = string
/**
 * Block that raised the error.
 *
 */
export type Program1 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def2 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute2 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser2 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback2 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role2 = string | null
/**
 * Current context
 *
 */
export type Context2 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId2 = string | null
export type Kind2 = "import"
/**
 * Name of the file to import.
 *
 */
export type Import = string
export type PdlTrace =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def3 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute3 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser3 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback3 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role3 = string | null
/**
 * Current context
 *
 */
export type Context3 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId3 = string | null
export type Kind3 = "include"
/**
 * Name of the file to include.
 *
 */
export type Include = string
export type PdlTrace1 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def4 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute4 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser4 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback4 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role4 = string | null
/**
 * Current context
 *
 */
export type Context4 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId4 = string | null
export type Kind4 = "read"
/**
 * Name of the file to read. If `None`, read the standard input.
 *
 */
export type Read = string | LocalizedExpression | null
/**
 * Message to prompt the user to enter a value.
 *
 */
export type Message = string | null
/**
 * Indicate if one or multiple lines should be read.
 *
 */
export type Multiline = boolean
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def5 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute5 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser5 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback5 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role of associated to the message.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role5 = string | null
/**
 * Current context
 *
 */
export type Context5 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId5 = string | null
export type Kind5 = "message"
/**
 * Content of the message.
 */
export type Content =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def6 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute6 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser6 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback6 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role6 = string | null
/**
 * Current context
 *
 */
export type Context6 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId6 = string | null
export type Kind6 = "object"
export type Object =
  | {
      [k: string]:
        | boolean
        | number
        | string
        | FunctionBlock
        | CallBlock
        | LitellmModelBlock
        | GraniteioModelBlock
        | CodeBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | MatchBlock
        | RepeatBlock
        | TextBlock
        | LastOfBlock
        | ArrayBlock
        | ObjectBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ImportBlock
        | ErrorBlock
        | EmptyBlock
        | null
    }
  | (
      | boolean
      | number
      | string
      | FunctionBlock
      | CallBlock
      | LitellmModelBlock
      | GraniteioModelBlock
      | CodeBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | MatchBlock
      | RepeatBlock
      | TextBlock
      | LastOfBlock
      | ArrayBlock
      | ObjectBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ImportBlock
      | ErrorBlock
      | EmptyBlock
      | null
    )[]
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def7 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute7 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser7 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback7 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role7 = string | null
/**
 * Current context
 *
 */
export type Context7 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId7 = string | null
export type Kind7 = "array"
/**
 * Elements of the array.
 */
export type Array = (
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
)[]
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def8 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute8 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser8 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback8 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role8 = string | null
/**
 * Current context
 *
 */
export type Context8 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId8 = string | null
export type Kind8 = "lastOf"
/**
 * Sequence of blocks to execute.
 */
export type Lastof = (
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
)[]
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def9 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute9 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser9 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback9 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role9 = string | null
/**
 * Current context
 *
 */
export type Context9 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId9 = string | null
export type Kind9 = "text"
/**
 * Body of the text.
 *
 */
export type Text =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | boolean
      | number
      | string
      | FunctionBlock
      | CallBlock
      | LitellmModelBlock
      | GraniteioModelBlock
      | CodeBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | MatchBlock
      | RepeatBlock
      | TextBlock
      | LastOfBlock
      | ArrayBlock
      | ObjectBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ImportBlock
      | ErrorBlock
      | EmptyBlock
      | null
    )[]
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def10 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute10 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser10 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback10 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role10 = string | null
/**
 * Current context
 *
 */
export type Context10 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId10 = string | null
export type Kind10 = "repeat"
/**
 * Arrays to iterate over.
 *
 */
export type For = {
  [k: string]: unknown[] | string | LocalizedExpression
} | null
/**
 * Condition to stay at the beginning of the loop.
 *
 */
export type While = boolean | string | LocalizedExpression
/**
 * Body of the loop.
 *
 */
export type Repeat =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Condition to exit at the end of the loop.
 *
 */
export type Until = boolean | string | LocalizedExpression
/**
 * Maximal number of iterations to perform.
 *
 */
export type MaxIterations = number | string | LocalizedExpression | null
/**
 * Define how to combine the result of each iteration.
 *
 */
export type Join = JoinText | JoinArray | JoinObject | JoinLastOf
/**
 * String concatenation of the result of each iteration.
 *
 */
export type As = "text"
/**
 * String used to concatenate each iteration of the loop.
 *
 */
export type With = string
/**
 * Return the result of each iteration as an array.
 *
 */
export type As1 = "array"
/**
 * Return the union of the objects created at each iteration.
 *
 */
export type As2 = "object"
/**
 * Return the result of the last iteration.
 *
 */
export type As3 = "lastOf"
export type PdlTrace2 =
  | (
      | boolean
      | number
      | string
      | FunctionBlock
      | CallBlock
      | LitellmModelBlock
      | GraniteioModelBlock
      | CodeBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | MatchBlock
      | RepeatBlock
      | TextBlock
      | LastOfBlock
      | ArrayBlock
      | ObjectBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ImportBlock
      | ErrorBlock
      | EmptyBlock
      | null
    )[]
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def11 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute11 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser11 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback11 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role11 = string | null
/**
 * Current context
 *
 */
export type Context11 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId11 = string | null
export type Kind11 = "match"
export type Case =
  | boolean
  | number
  | string
  | OrPattern
  | ArrayPattern
  | ObjectPattern
  | AnyPattern
  | null
export type Def12 = string | null
export type Def13 = string | null
export type Def14 = string | null
export type Def15 = string | null
export type Any = null
export type Array1 = (
  | boolean
  | number
  | string
  | OrPattern
  | ArrayPattern
  | ObjectPattern
  | AnyPattern
  | null
)[]
export type Anyof = (
  | boolean
  | number
  | string
  | OrPattern
  | ArrayPattern
  | ObjectPattern
  | AnyPattern
  | null
)[]
export type If = boolean | string | LocalizedExpression | null
export type Then =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
export type PdlCaseResult = boolean | null
export type PdlIfResult = boolean | null
export type PdlMatched = boolean | null
/**
 * List of cases to match.
 *
 */
export type With1 = MatchCase[]
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def16 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute12 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser12 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback12 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role12 = string | null
/**
 * Current context
 *
 */
export type Context12 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId12 = string | null
export type Kind12 = "if"
/**
 * Condition.
 *
 */
export type If1 = boolean | string | LocalizedExpression
/**
 * Branch to execute if the condition is true.
 *
 */
export type Then1 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Branch to execute if the condition is false.
 *
 */
export type Else =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
export type IfResult = boolean | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def17 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute13 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser13 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback13 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role13 = string | null
/**
 * Current context
 *
 */
export type Context13 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId13 = string | null
export type Kind13 = "data"
/**
 * Do not evaluate expressions inside strings.
 */
export type Raw = boolean
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def18 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute14 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser14 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback14 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role14 = string | null
/**
 * Current context
 *
 */
export type Context14 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId14 = string | null
export type Kind14 = "get"
/**
 * Name of the variable to access.
 */
export type Get = string
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def19 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute15 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser15 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback15 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role15 = string | null
/**
 * Current context
 *
 */
export type Context15 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId15 = string | null
export type Kind15 = "code"
/**
 * Programming language of the code.
 *
 */
export type Lang = "python" | "command" | "jinja" | "pdl"
/**
 * Code to execute.
 *
 */
export type Code =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def20 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute16 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser16 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback16 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role16 = string | null
/**
 * Current context
 *
 */
export type Context16 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId16 = string | null
export type Kind16 = "model"
/**
 * Messages to send to the model.
 *
 */
export type Input =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Variable where to store the raw response of the model.
 *
 */
export type Modelresponse = string | null
export type PdlTrace3 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Optional field to ensure that the block is using granite-io.
 *
 */
export type Platform = "granite-io"
/**
 * Backend name and configuration.
 *
 */
export type Backend =
  | string
  | {
      [k: string]: unknown
    }
  | LocalizedExpression
/**
 * IO Processor name.
 *
 */
export type Processor = string | LocalizedExpression | null
/**
 * Parameters sent to the model.
 *
 */
export type Parameters =
  | {
      [k: string]: unknown
    }
  | string
  | LocalizedExpression
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def21 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute17 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser17 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback17 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role17 = string | null
/**
 * Current context
 *
 */
export type Context17 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId17 = string | null
export type Kind17 = "model"
/**
 * Name of the model following the LiteLLM convention.
 *
 */
export type Model1 = string | LocalizedExpression
/**
 * Messages to send to the model.
 *
 */
export type Input1 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Variable where to store the raw response of the model.
 *
 */
export type Modelresponse1 = string | null
export type PdlTrace4 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Optional field to ensure that the block is using LiteLLM.
 *
 */
export type Platform1 = "litellm"
/**
 * Parameters to send to the model.
 *
 */
export type Parameters1 =
  | LitellmParameters
  | {
      [k: string]: unknown
    }
  | string
  | LocalizedExpression
  | null
export type Timeout = number | string | null
export type Temperature = number | string | null
export type TopP = number | string | null
export type N = number | string | null
export type Stop = string | string[] | null
export type MaxTokens = number | string | null
export type PresencePenalty = number | string | null
export type FrequencyPenalty = number | string | null
export type LogitBias =
  | {
      [k: string]: unknown
    }
  | string
  | null
export type User = string | null
export type ResponseFormat =
  | {
      [k: string]: unknown
    }
  | string
  | null
export type Seed = number | string | null
export type Tools = unknown[] | string | null
export type ToolChoice =
  | string
  | {
      [k: string]: unknown
    }
  | null
export type Logprobs = boolean | string | null
export type TopLogprobs = number | string | null
export type ParallelToolCalls = boolean | string | null
export type ExtraHeaders =
  | {
      [k: string]: unknown
    }
  | string
  | null
export type Functions = unknown[] | string | null
export type FunctionCall = string | null
export type BaseUrl = string | null
export type ApiVersion = string | null
export type ApiKey = string | null
export type ModelList = unknown[] | string | null
export type MockResponse = string | null
export type CustomLlmProvider = string | null
export type MaxRetries = number | string | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def22 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute18 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser18 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback18 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role18 = string | null
/**
 * Current context
 *
 */
export type Context18 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId18 = string | null
export type Kind18 = "call"
export type PdlTrace5 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Name of the variable used to store the result of the execution of the block.
 *
 */
export type Def23 = string | null
/**
 * Indicate if the block contributes to the result and background context.
 *
 */
export type Contribute19 = (
  | ContributeTarget
  | {
      [k: string]: ContributeValue
    }
)[]
/**
 * Parser to use to construct a value out of a string result.
 */
export type Parser19 =
  | ("json" | "jsonl" | "yaml")
  | PdlParser
  | RegexParser
  | null
/**
 * Block to execute in case of error.
 *
 */
export type Fallback19 =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
/**
 * Role associated to the block and sub-blocks.
 * Typical roles are `system`, `user`, and `assistant`,
 * but there may be other roles such as `available_tools`.
 */
export type Role19 = string | null
/**
 * Current context
 *
 */
export type Context19 =
  | {
      [k: string]: unknown
    }[]
  | null
/**
 * Unique identifier for this block
 *
 */
export type PdlId19 = string | null
export type Kind19 = "function"
/**
 * Functions parameters with their types.
 *
 */
export type Function = {
  [k: string]: unknown
} | null
/**
 * Body of the function
 *
 */
export type Return =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null
export type PdlBlock =
  | boolean
  | number
  | string
  | FunctionBlock
  | CallBlock
  | LitellmModelBlock
  | GraniteioModelBlock
  | CodeBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | MatchBlock
  | RepeatBlock
  | TextBlock
  | LastOfBlock
  | ArrayBlock
  | ObjectBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ImportBlock
  | ErrorBlock
  | EmptyBlock
  | null

/**
 * Function declaration.
 */
export interface FunctionBlock {
  description?: Description
  spec?: Spec
  defs?: Defs
  def?: Def23
  contribute?: Contribute19
  parser?: Parser19
  fallback?: Fallback19
  role?: Role19
  context?: Context19
  pdl__id?: PdlId19
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind19
  function: Function
  return: Return
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Calling a function.
 */
export interface CallBlock {
  description?: Description1
  spec?: Spec1
  defs?: Defs1
  def?: Def22
  contribute?: Contribute18
  parser?: Parser18
  fallback?: Fallback18
  role?: Role18
  context?: Context18
  pdl__id?: PdlId18
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind18
  call: unknown
  args?: unknown
  pdl__trace?: PdlTrace5
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec1 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs1 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Call an LLM through [the LiteLLM API](https://docs.litellm.ai/).
 *
 * Example:
 * ```PDL
 * - model: ollama/granite-code:8b
 *   parameters:
 *     stop: ['!']
 * ```
 */
export interface LitellmModelBlock {
  description?: Description2
  spec?: Spec2
  defs?: Defs2
  def?: Def21
  contribute?: Contribute17
  parser?: Parser17
  fallback?: Fallback17
  role?: Role17
  context?: Context17
  pdl__id?: PdlId17
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind17
  model: Model1
  input?: Input1
  modelResponse?: Modelresponse1
  pdl__trace?: PdlTrace4
  platform?: Platform1
  parameters?: Parameters1
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec2 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs2 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Call an LLM through the granite-io API.
 */
export interface GraniteioModelBlock {
  description?: Description3
  spec?: Spec3
  defs?: Defs3
  def?: Def20
  contribute?: Contribute16
  parser?: Parser16
  fallback?: Fallback16
  role?: Role16
  context?: Context16
  pdl__id?: PdlId16
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind16
  model: unknown
  input?: Input
  modelResponse?: Modelresponse
  pdl__trace?: PdlTrace3
  platform?: Platform
  backend: Backend
  processor?: Processor
  parameters?: Parameters
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec3 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs3 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Execute a piece of code.
 *
 * Example:
 * ```PDL
 * - def: N
 *   lang: python
 *   code: |
 *     import random
 *     # (In PDL, set `result` to the output you wish for your code block.)
 *     result = random.randint(1, 20)
 * ```
 */
export interface CodeBlock {
  description?: Description4
  spec?: Spec4
  defs?: Defs4
  def?: Def19
  contribute?: Contribute15
  parser?: Parser15
  fallback?: Fallback15
  role?: Role15
  context?: Context15
  pdl__id?: PdlId15
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind15
  lang: Lang
  code: Code
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec4 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs4 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Get the value of a variable.
 *
 * The GetBlock is deprecated.  Use DataBlock instead.
 */
export interface GetBlock {
  description?: Description5
  spec?: Spec5
  defs?: Defs5
  def?: Def18
  contribute?: Contribute14
  parser?: Parser14
  fallback?: Fallback14
  role?: Role14
  context?: Context14
  pdl__id?: PdlId14
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind14
  get: Get
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec5 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs5 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Arbitrary value, equivalent to JSON.
 *
 * Example. As part of a `defs` section, set `numbers` to the list `[1, 2, 3, 4]`:
 * ```PDL
 * defs:
 *   numbers:
 *     data: [1, 2, 3, 4]
 * ```
 *
 * Example.  Evaluate `${ TEST.answer }` in
 * [Jinja](https://jinja.palletsprojects.com/en/stable/), passing
 * the result to a regex parser with capture groups.  Set
 * `EXTRACTED_GROUND_TRUTH` to an object with attribute `answer`,
 * a string, containing the value of the capture group.
 * ```PDL
 * - data: ${ TEST.answer }
 *   parser:
 *     regex: "(.|\n)*#### (?P<answer>([0-9])*)\n*"
 *     spec:
 *       answer: str
 *   def: EXTRACTED_GROUND_TRUTH
 * ```
 */
export interface DataBlock {
  description?: Description6
  spec?: Spec6
  defs?: Defs6
  def?: Def17
  contribute?: Contribute13
  parser?: Parser13
  fallback?: Fallback13
  role?: Role13
  context?: Context13
  pdl__id?: PdlId13
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind13
  data: unknown
  raw?: Raw
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec6 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs6 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Conditional control structure.
 *
 * Example:
 * ```PDL
 * - if: ${ eval == 'no' }
 *   then:
 *     text:
 *     - read:
 *       message: "Why not?\n"
 * ```
 */
export interface IfBlock {
  description?: Description7
  spec?: Spec7
  defs?: Defs7
  def?: Def16
  contribute?: Contribute12
  parser?: Parser12
  fallback?: Fallback12
  role?: Role12
  context?: Context12
  pdl__id?: PdlId12
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind12
  if: If1
  then: Then1
  else?: Else
  if_result?: IfResult
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec7 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs7 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Match control structure.
 */
export interface MatchBlock {
  description?: Description8
  spec?: Spec8
  defs?: Defs8
  def?: Def11
  contribute?: Contribute11
  parser?: Parser11
  fallback?: Fallback11
  role?: Role11
  context?: Context11
  pdl__id?: PdlId11
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind11
  match: unknown
  with: With1
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec8 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs8 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Repeat the execution of a block.
 *
 * For loop example:
 * ```PDL
 * for:
 *     number: [1, 2, 3, 4]
 *     name: ["Bob", "Carol", "David", "Ernest"]
 * repeat:
 *     "${ name }'s number is ${ number }\n"
 * ```
 */
export interface RepeatBlock {
  description?: Description9
  spec?: Spec9
  defs?: Defs9
  def?: Def10
  contribute?: Contribute10
  parser?: Parser10
  fallback?: Fallback10
  role?: Role10
  context?: Context10
  pdl__id?: PdlId10
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind10
  for?: For
  while?: While
  repeat: Repeat
  until?: Until
  max_iterations?: MaxIterations
  join?: Join
  pdl__trace?: PdlTrace2
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec9 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs9 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Create the concatenation of the stringify version of the result of each block of the list of blocks.
 */
export interface TextBlock {
  description?: Description10
  spec?: Spec10
  defs?: Defs10
  def?: Def9
  contribute?: Contribute9
  parser?: Parser9
  fallback?: Fallback9
  role?: Role9
  context?: Context9
  pdl__id?: PdlId9
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind9
  text: Text
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec10 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs10 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Return the value of the last block if the list of blocks.
 */
export interface LastOfBlock {
  description?: Description11
  spec?: Spec11
  defs?: Defs11
  def?: Def8
  contribute?: Contribute8
  parser?: Parser8
  fallback?: Fallback8
  role?: Role8
  context?: Context8
  pdl__id?: PdlId8
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind8
  lastOf: Lastof
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec11 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs11 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Return the array of values computed by each block of the list of blocks.
 */
export interface ArrayBlock {
  description?: Description12
  spec?: Spec12
  defs?: Defs12
  def?: Def7
  contribute?: Contribute7
  parser?: Parser7
  fallback?: Fallback7
  role?: Role7
  context?: Context7
  pdl__id?: PdlId7
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind7
  array: Array
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec12 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs12 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Return the object where the value of each field is defined by a block. If the body of the object is an array, the resulting object is the union of the objects computed by each element of the array.
 */
export interface ObjectBlock {
  description?: Description13
  spec?: Spec13
  defs?: Defs13
  def?: Def6
  contribute?: Contribute6
  parser?: Parser6
  fallback?: Fallback6
  role?: Role6
  context?: Context6
  pdl__id?: PdlId6
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind6
  object: Object
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec13 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs13 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Create a message.
 */
export interface MessageBlock {
  description?: Description14
  spec?: Spec14
  defs?: Defs14
  def?: Def5
  contribute?: Contribute5
  parser?: Parser5
  fallback?: Fallback5
  role: Role5
  context?: Context5
  pdl__id?: PdlId5
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind5
  content: Content
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec14 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs14 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Read from a file or standard input.
 */
export interface ReadBlock {
  description?: Description15
  spec?: Spec15
  defs?: Defs15
  def?: Def4
  contribute?: Contribute4
  parser?: Parser4
  fallback?: Fallback4
  role?: Role4
  context?: Context4
  pdl__id?: PdlId4
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind4
  read: Read
  message?: Message
  multiline?: Multiline
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec15 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs15 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Include a PDL file.
 */
export interface IncludeBlock {
  description?: Description16
  spec?: Spec16
  defs?: Defs16
  def?: Def3
  contribute?: Contribute3
  parser?: Parser3
  fallback?: Fallback3
  role?: Role3
  context?: Context3
  pdl__id?: PdlId3
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind3
  include: Include
  pdl__trace?: PdlTrace1
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec16 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs16 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Import a PDL file.
 */
export interface ImportBlock {
  description?: Description17
  spec?: Spec17
  defs?: Defs17
  def?: Def2
  contribute?: Contribute2
  parser?: Parser2
  fallback?: Fallback2
  role?: Role2
  context?: Context2
  pdl__id?: PdlId2
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind2
  import: Import
  pdl__trace?: PdlTrace
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec17 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs17 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Block representing an error generated at runtime.
 */
export interface ErrorBlock {
  description?: Description18
  spec?: Spec18
  defs?: Defs18
  def?: Def1
  contribute?: Contribute1
  parser?: Parser1
  fallback?: Fallback1
  role?: Role1
  context?: Context1
  pdl__id?: PdlId1
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind1
  msg: Msg
  program: Program1
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec18 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs18 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
/**
 * Block without an action. It can contain definitions.
 */
export interface EmptyBlock {
  description?: Description19
  spec?: Spec19
  defs?: Defs19
  def?: Def
  contribute?: Contribute
  parser?: Parser
  fallback?: Fallback
  role?: Role
  context?: Context
  pdl__id?: PdlId
  pdl__result?: unknown
  pdl__location?: PdlLocationType | null
  pdl__timing?: PdlTiming | null
  kind?: Kind
}
/**
 * Type specification of the result of the block.
 *
 */
export interface Spec19 {
  [k: string]: unknown
}
/**
 * Set of definitions executed before the execution of the block.
 *
 */
export interface Defs19 {
  [k: string]:
    | boolean
    | number
    | string
    | FunctionBlock
    | CallBlock
    | LitellmModelBlock
    | GraniteioModelBlock
    | CodeBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | MatchBlock
    | RepeatBlock
    | TextBlock
    | LastOfBlock
    | ArrayBlock
    | ObjectBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ImportBlock
    | ErrorBlock
    | EmptyBlock
    | null
}
export interface ContributeValue {
  value: Value
}
export interface PdlParser {
  description?: Description20
  spec?: Spec20
  pdl: Pdl
}
/**
 * A regular expression parser
 */
export interface RegexParser {
  description?: Description21
  spec?: Spec21
  regex: Regex
  mode?: Mode
}
/**
 * Internal data structure to keep track of the source location information.
 */
export interface PdlLocationType {
  path: Path
  file: File
  table: Table
}
export interface Table {
  [k: string]: number
}
/**
 * Internal data structure to record timing information in the trace.
 */
export interface PdlTiming {
  start_nanos?: StartNanos
  end_nanos?: EndNanos
  first_use_nanos?: FirstUseNanos
  timezone?: Timezone
}
export interface LocalizedExpression {
  expr: Expr
  pdl__location?: PdlLocationType | null
}
export interface Expr {
  [k: string]: unknown
}
export interface JoinText {
  as?: As
  with?: With
}
export interface JoinArray {
  as: As1
}
export interface JoinObject {
  as: As2
}
export interface JoinLastOf {
  as: As3
}
/**
 * Case of a match.
 */
export interface MatchCase {
  case?: Case
  if?: If
  then: Then
  pdl__case_result?: PdlCaseResult
  pdl__if_result?: PdlIfResult
  pdl__matched?: PdlMatched
}
export interface OrPattern {
  def?: Def12
  anyOf: Anyof
}
export interface ArrayPattern {
  def?: Def13
  array: Array1
}
export interface ObjectPattern {
  def?: Def14
  object: Object1
}
export interface Object1 {
  [k: string]:
    | boolean
    | number
    | string
    | OrPattern
    | ArrayPattern
    | ObjectPattern
    | AnyPattern
    | null
}
export interface AnyPattern {
  def?: Def15
  any: Any
}
/**
 * Parameters passed to LiteLLM. More details at [https://docs.litellm.ai/docs/completion/input](https://docs.litellm.ai/docs/completion/input).
 *
 * Note that not all models and platforms accept all parameters.
 */
export interface LitellmParameters {
  timeout?: Timeout
  temperature?: Temperature
  top_p?: TopP
  n?: N
  stop?: Stop
  max_tokens?: MaxTokens
  presence_penalty?: PresencePenalty
  frequency_penalty?: FrequencyPenalty
  logit_bias?: LogitBias
  user?: User
  response_format?: ResponseFormat
  seed?: Seed
  tools?: Tools
  tool_choice?: ToolChoice
  logprobs?: Logprobs
  top_logprobs?: TopLogprobs
  parallel_tool_calls?: ParallelToolCalls
  extra_headers?: ExtraHeaders
  functions?: Functions
  function_call?: FunctionCall
  base_url?: BaseUrl
  api_version?: ApiVersion
  api_key?: ApiKey
  model_list?: ModelList
  mock_response?: MockResponse
  custom_llm_provider?: CustomLlmProvider
  max_retries?: MaxRetries
  [k: string]: unknown
}
