/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PDLSchemas = Program | PdlBlock | PdlBlocks;
/**
 * Prompt Description Program (PDL)
 */
export type Program =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock;
export type Description = string | null;
export type Description1 = string | null;
export type Description2 = string | null;
export type Description3 = string | null;
export type Description4 = string | null;
export type Description5 = string | null;
export type Description6 = string | null;
export type Description7 = string | null;
export type Description8 = string | null;
export type Description9 = string | null;
export type Description10 = string | null;
export type Description11 = string | null;
export type Description12 = string | null;
export type Description13 = string | null;
export type Description14 = string | null;
export type Description15 = string | null;
export type Description16 = string | null;
export type Def = string | null;
export type ShowResult = boolean;
export type Parser = ("json" | "yaml") | null;
export type Kind = "empty";
export type Def1 = string | null;
export type ShowResult1 = boolean;
export type Parser1 = ("json" | "yaml") | null;
export type Kind1 = "error";
export type Msg = string;
export type Program1 =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def2 = string | null;
export type ShowResult2 = boolean;
export type Parser2 = ("json" | "yaml") | null;
export type Kind2 = "parse";
export type From =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type With =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Mode = "pdl" | "regex";
export type Def3 = string | null;
export type ShowResult3 = boolean;
export type Parser3 = ("json" | "yaml") | null;
export type Kind3 = "include";
export type Include = string;
export type Trace =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Def4 = string | null;
export type ShowResult4 = boolean;
export type Parser4 = ("json" | "yaml") | null;
export type Kind4 = "read";
export type Read = string | null;
export type Message = string | null;
export type Multiline = boolean;
export type Def5 = string | null;
export type ShowResult5 = boolean;
export type Parser5 = ("json" | "yaml") | null;
export type Kind5 = "document";
export type Document =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def6 = string | null;
export type ShowResult6 = boolean;
export type Parser6 = ("json" | "yaml") | null;
export type Kind6 = "for";
export type Repeat =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Trace1 =
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | string
          | FunctionBlock
          | CallBlock
          | ModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | ReadBlock
          | IncludeBlock
          | ParseBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def7 = string | null;
export type ShowResult7 = boolean;
export type Parser7 = ("json" | "yaml") | null;
export type Kind7 = "repeat_until";
export type Repeat1 =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Trace2 =
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | string
          | FunctionBlock
          | CallBlock
          | ModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | ReadBlock
          | IncludeBlock
          | ParseBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def8 = string | null;
export type ShowResult8 = boolean;
export type Parser8 = ("json" | "yaml") | null;
export type Kind8 = "repeat";
export type Repeat2 =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type NumIterations = number;
export type Trace3 =
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | string
          | FunctionBlock
          | CallBlock
          | ModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | ReadBlock
          | IncludeBlock
          | ParseBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def9 = string | null;
export type ShowResult9 = boolean;
export type Parser9 = ("json" | "yaml") | null;
export type Kind9 = "if";
export type Then =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Else =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type IfResult = boolean | null;
export type Def10 = string | null;
export type ShowResult10 = boolean;
export type Parser10 = ("json" | "yaml") | null;
export type Kind10 = "data";
export type Def11 = string | null;
export type ShowResult11 = boolean;
export type Parser11 = ("json" | "yaml") | null;
export type Kind11 = "get";
export type Get = string;
export type Def12 = string | null;
export type ShowResult12 = boolean;
export type Parser12 = ("json" | "yaml") | null;
export type Kind12 = "api";
export type Api = string;
export type Url = string;
export type Input =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def13 = string | null;
export type ShowResult13 = boolean;
export type Parser13 = ("json" | "yaml") | null;
export type Kind13 = "code";
export type Lan = string;
export type Code =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def14 = string | null;
export type ShowResult14 = boolean;
export type Parser14 = ("json" | "yaml") | null;
export type Kind14 = "model";
export type Model = string;
export type Input1 =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type PromptId = string | null;
export type BeamWidth = number | null;
export type DecodingMethod = "greedy" | "sample";
export type IncludeStopSequence = boolean | null;
export type DecayFactor = number | null;
export type StartIndex = number | null;
export type MaxNewTokens = number | null;
export type MinNewTokens = number | null;
export type RandomSeed = number | null;
export type RepetitionPenalty = number | null;
export type GeneratedTokens = boolean | null;
export type InputParameters = boolean | null;
export type InputText = boolean | null;
export type InputTokens = boolean | null;
export type TokenLogprobs = boolean | null;
export type TokenRanks = boolean | null;
export type TopNTokens = number | null;
export type StopSequences =
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | null;
export type Temperature = number | null;
export type TimeLimit = number | null;
export type TopK = number | null;
export type TopPNucleusSampling = number | null;
export type TruncateInputTokens = number | null;
export type TypicalP = number | null;
export type Enabled = boolean | null;
export type SendTokens = boolean | null;
export type Threshold = number | null;
export type Enabled1 = boolean | null;
export type SendTokens1 = boolean | null;
export type Threshold1 = number | null;
export type Enabled2 = boolean | null;
export type SendTokens2 = boolean | null;
export type Threshold2 = number | null;
export type Enabled3 = boolean | null;
export type SendTokens3 = boolean | null;
export type Threshold3 = number | null;
export type ExampleFileIds =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | null;
export type Def15 = string | null;
export type ShowResult15 = boolean;
export type Parser15 = ("json" | "yaml") | null;
export type Kind15 = "call";
export type Call = string;
export type Trace4 =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Def16 = string | null;
export type ShowResult16 = boolean;
export type Parser16 = ("json" | "yaml") | null;
export type Kind16 = "function";
export type Function = {
  [k: string]: unknown;
} | null;
export type Return =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Scope = {
  [k: string]: unknown;
} | null;
export type PdlBlock =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock;
export type PdlBlocks =
  | string
  | FunctionBlock
  | CallBlock
  | ModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | ReadBlock
  | IncludeBlock
  | ParseBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | string
      | FunctionBlock
      | CallBlock
      | ModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | ReadBlock
      | IncludeBlock
      | ParseBlock
      | ErrorBlock
      | EmptyBlock
    )[];

export interface FunctionBlock {
  description?: Description;
  spec?: Spec;
  defs?: Defs;
  def?: Def16;
  show_result?: ShowResult16;
  result?: unknown;
  parser?: Parser16;
  kind?: Kind16;
  function: Function;
  return: Return;
  scope?: Scope;
}
export interface Spec {
  [k: string]: unknown;
}
export interface Defs {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface CallBlock {
  description?: Description1;
  spec?: Spec1;
  defs?: Defs1;
  def?: Def15;
  show_result?: ShowResult15;
  result?: unknown;
  parser?: Parser15;
  kind?: Kind15;
  call: Call;
  args?: Args;
  trace?: Trace4;
}
export interface Spec1 {
  [k: string]: unknown;
}
export interface Defs1 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ModelBlock {
  description?: Description2;
  spec?: Spec2;
  defs?: Defs2;
  def?: Def14;
  show_result?: ShowResult14;
  result?: unknown;
  parser?: Parser14;
  kind?: Kind14;
  model: Model;
  input?: Input1;
  prompt_id?: PromptId;
  parameters?: PDLTextGenerationParameters | null;
  moderations?: ModerationParameters | null;
  data?: PromptTemplateData | null;
  constraints?: Constraints;
}
export interface Spec2 {
  [k: string]: unknown;
}
export interface Defs2 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface CodeBlock {
  description?: Description3;
  spec?: Spec3;
  defs?: Defs3;
  def?: Def13;
  show_result?: ShowResult13;
  result?: unknown;
  parser?: Parser13;
  kind?: Kind13;
  lan: Lan;
  code: Code;
}
export interface Spec3 {
  [k: string]: unknown;
}
export interface Defs3 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ApiBlock {
  description?: Description4;
  spec?: Spec4;
  defs?: Defs4;
  def?: Def12;
  show_result?: ShowResult12;
  result?: unknown;
  parser?: Parser12;
  kind?: Kind12;
  api: Api;
  url: Url;
  input: Input;
}
export interface Spec4 {
  [k: string]: unknown;
}
export interface Defs4 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface GetBlock {
  description?: Description5;
  spec?: Spec5;
  defs?: Defs5;
  def?: Def11;
  show_result?: ShowResult11;
  result?: unknown;
  parser?: Parser11;
  kind?: Kind11;
  get: Get;
}
export interface Spec5 {
  [k: string]: unknown;
}
export interface Defs5 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface DataBlock {
  description?: Description6;
  spec?: Spec6;
  defs?: Defs6;
  def?: Def10;
  show_result?: ShowResult10;
  result?: unknown;
  parser?: Parser10;
  kind?: Kind10;
  data: Data;
}
export interface Spec6 {
  [k: string]: unknown;
}
export interface Defs6 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface IfBlock {
  description?: Description7;
  spec?: Spec7;
  defs?: Defs7;
  def?: Def9;
  show_result?: ShowResult9;
  result?: unknown;
  parser?: Parser9;
  kind?: Kind9;
  if: If;
  then: Then;
  else?: Else;
  if_result?: IfResult;
}
export interface Spec7 {
  [k: string]: unknown;
}
export interface Defs7 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface RepeatBlock {
  description?: Description8;
  spec?: Spec8;
  defs?: Defs8;
  def?: Def8;
  show_result?: ShowResult8;
  result?: unknown;
  parser?: Parser8;
  kind?: Kind8;
  repeat: Repeat2;
  num_iterations: NumIterations;
  trace?: Trace3;
}
export interface Spec8 {
  [k: string]: unknown;
}
export interface Defs8 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface RepeatUntilBlock {
  description?: Description9;
  spec?: Spec9;
  defs?: Defs9;
  def?: Def7;
  show_result?: ShowResult7;
  result?: unknown;
  parser?: Parser7;
  kind?: Kind7;
  repeat: Repeat1;
  until: Until;
  trace?: Trace2;
}
export interface Spec9 {
  [k: string]: unknown;
}
export interface Defs9 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ForBlock {
  description?: Description10;
  spec?: Spec10;
  defs?: Defs10;
  def?: Def6;
  show_result?: ShowResult6;
  result?: unknown;
  parser?: Parser6;
  kind?: Kind6;
  for: For;
  repeat: Repeat;
  trace?: Trace1;
}
export interface Spec10 {
  [k: string]: unknown;
}
export interface Defs10 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface DocumentBlock {
  description?: Description11;
  spec?: Spec11;
  defs?: Defs11;
  def?: Def5;
  show_result?: ShowResult5;
  result?: unknown;
  parser?: Parser5;
  kind?: Kind5;
  document: Document;
}
export interface Spec11 {
  [k: string]: unknown;
}
export interface Defs11 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ReadBlock {
  description?: Description12;
  spec?: Spec12;
  defs?: Defs12;
  def?: Def4;
  show_result?: ShowResult4;
  result?: unknown;
  parser?: Parser4;
  kind?: Kind4;
  read: Read;
  message?: Message;
  multiline?: Multiline;
}
export interface Spec12 {
  [k: string]: unknown;
}
export interface Defs12 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface IncludeBlock {
  description?: Description13;
  spec?: Spec13;
  defs?: Defs13;
  def?: Def3;
  show_result?: ShowResult3;
  result?: unknown;
  parser?: Parser3;
  kind?: Kind3;
  include: Include;
  trace?: Trace;
}
export interface Spec13 {
  [k: string]: unknown;
}
export interface Defs13 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ParseBlock {
  description?: Description14;
  spec?: Spec14;
  defs?: Defs14;
  def?: Def2;
  show_result?: ShowResult2;
  result?: unknown;
  parser?: Parser2;
  kind?: Kind2;
  parse: Parse;
  from?: From;
  with: With;
  mode?: Mode;
}
export interface Spec14 {
  [k: string]: unknown;
}
export interface Defs14 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ErrorBlock {
  description?: Description15;
  spec?: Spec15;
  defs?: Defs15;
  def?: Def1;
  show_result?: ShowResult1;
  result?: unknown;
  parser?: Parser1;
  kind?: Kind1;
  msg: Msg;
  program: Program1;
}
export interface Spec15 {
  [k: string]: unknown;
}
export interface Defs15 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface EmptyBlock {
  description?: Description16;
  spec?: Spec16;
  defs?: Defs16;
  def?: Def;
  show_result?: ShowResult;
  result?: unknown;
  parser?: Parser;
  kind?: Kind;
}
export interface Spec16 {
  [k: string]: unknown;
}
export interface Defs16 {
  [k: string]:
    | string
    | FunctionBlock
    | CallBlock
    | ModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | ReadBlock
    | IncludeBlock
    | ParseBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | string
        | FunctionBlock
        | CallBlock
        | ModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | ReadBlock
        | IncludeBlock
        | ParseBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface Parse {
  [k: string]: unknown;
}
export interface For {
  [k: string]: unknown;
}
export interface Until {
  [k: string]: unknown;
}
export interface If {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
export interface PDLTextGenerationParameters {
  beam_width?: BeamWidth;
  decoding_method?: DecodingMethod | null;
  include_stop_sequence?: IncludeStopSequence;
  length_penalty?: LengthPenalty | null;
  max_new_tokens?: MaxNewTokens;
  min_new_tokens?: MinNewTokens;
  random_seed?: RandomSeed;
  repetition_penalty?: RepetitionPenalty;
  return_options?: TextGenerationReturnOptions | null;
  stop_sequences?: StopSequences;
  temperature?: Temperature;
  time_limit?: TimeLimit;
  top_k?: TopK;
  top_p?: TopPNucleusSampling;
  truncate_input_tokens?: TruncateInputTokens;
  typical_p?: TypicalP;
}
export interface LengthPenalty {
  decay_factor?: DecayFactor;
  start_index?: StartIndex;
  [k: string]: unknown;
}
export interface TextGenerationReturnOptions {
  generated_tokens?: GeneratedTokens;
  input_parameters?: InputParameters;
  input_text?: InputText;
  input_tokens?: InputTokens;
  token_logprobs?: TokenLogprobs;
  token_ranks?: TokenRanks;
  top_n_tokens?: TopNTokens;
  [k: string]: unknown;
}
export interface ModerationParameters {
  hap?: ModerationHAP | null;
  social_bias?: ModerationSocialBias | null;
  [k: string]: unknown;
}
export interface ModerationHAP {
  input?: ModerationHAPInput | null;
  output?: ModerationHAPOutput | null;
  [k: string]: unknown;
}
export interface ModerationHAPInput {
  enabled?: Enabled;
  send_tokens?: SendTokens;
  threshold?: Threshold;
  [k: string]: unknown;
}
export interface ModerationHAPOutput {
  enabled?: Enabled1;
  send_tokens?: SendTokens1;
  threshold?: Threshold1;
  [k: string]: unknown;
}
export interface ModerationSocialBias {
  input?: ModerationSocialBiasInput | null;
  output?: ModerationSocialBiasOutput | null;
  [k: string]: unknown;
}
export interface ModerationSocialBiasInput {
  enabled?: Enabled2;
  send_tokens?: SendTokens2;
  threshold?: Threshold2;
  [k: string]: unknown;
}
export interface ModerationSocialBiasOutput {
  enabled?: Enabled3;
  send_tokens?: SendTokens3;
  threshold?: Threshold3;
  [k: string]: unknown;
}
export interface PromptTemplateData {
  example_file_ids?: ExampleFileIds;
  [k: string]: unknown;
}
export interface Constraints {
  [k: string]: unknown;
}
export interface Args {
  [k: string]: unknown;
}
