/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PDLSchemas = Program | PdlBlock | PdlBlocks;
/**
 * Prompt Declaration Language program (PDL)
 */
export type Program =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock;
export type Description = string | null;
export type Description1 = string | null;
export type Description2 = string | null;
export type Description3 = string | null;
export type Description4 = string | null;
export type Description5 = string | null;
export type Description6 = string | null;
export type Description7 = string | null;
export type Description8 = string | null;
export type Description9 = string | null;
export type Description10 = string | null;
export type Description11 = string | null;
export type Description12 = string | null;
export type Description13 = string | null;
export type Description14 = string | null;
export type Description15 = string | null;
export type Description16 = string | null;
export type Description17 = string | null;
export type Description18 = string | null;
export type Description19 = string | null;
export type Description20 = string | null;
export type Def = string | null;
export type ShowResult = boolean;
export type Parser = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Description21 = string | null;
export type Spec21 = {
  [k: string]: unknown;
} | null;
export type Pdl =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Description22 = string | null;
export type Spec22 = {
  [k: string]: unknown;
} | null;
export type Regex = string;
export type Mode = "search" | "match" | "fullmatch" | "split" | "findall";
export type Fallback =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role = string | null;
export type Path = string[];
export type File = string;
export type HasError = boolean;
export type Kind = "empty";
export type Def1 = string | null;
export type ShowResult1 = boolean;
export type Parser1 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role1 = string | null;
export type HasError1 = boolean;
export type Kind1 = "error";
export type Msg = string;
export type Program1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def2 = string | null;
export type ShowResult2 = boolean;
export type Parser2 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role2 = string | null;
export type HasError2 = boolean;
export type Kind2 = "include";
export type Include = string;
export type Trace =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Def3 = string | null;
export type ShowResult3 = boolean;
export type Parser3 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback3 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role3 = string | null;
export type HasError3 = boolean;
export type Kind3 = "read";
export type Read = string | null;
export type Message = string | null;
export type Multiline = boolean;
export type Def4 = string | null;
export type ShowResult4 = boolean;
export type Parser4 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback4 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role4 = string | null;
export type HasError4 = boolean;
export type Kind4 = "message";
export type Content =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def5 = string | null;
export type ShowResult5 = boolean;
export type Parser5 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback5 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role5 = string | null;
export type HasError5 = boolean;
export type Kind5 = "array";
export type Array =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def6 = string | null;
export type ShowResult6 = boolean;
export type Parser6 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback6 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role6 = string | null;
export type HasError6 = boolean;
export type Kind6 = "sequence";
export type Sequence =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def7 = string | null;
export type ShowResult7 = boolean;
export type Parser7 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback7 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role7 = string | null;
export type HasError7 = boolean;
export type Kind7 = "document";
export type Document =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def8 = string | null;
export type ShowResult8 = boolean;
export type Parser8 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback8 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role8 = string | null;
export type HasError8 = boolean;
export type Kind8 = "for";
export type Repeat =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type IterationType = "sequence" | "array" | "document";
export type Trace1 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | LitellmModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | MessageBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def9 = string | null;
export type ShowResult9 = boolean;
export type Parser9 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback9 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role9 = string | null;
export type HasError9 = boolean;
export type Kind9 = "repeat_until";
export type Repeat1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Trace2 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | LitellmModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | MessageBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def10 = string | null;
export type ShowResult10 = boolean;
export type Parser10 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback10 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role10 = string | null;
export type HasError10 = boolean;
export type Kind10 = "repeat";
export type Repeat2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type NumIterations = number;
export type Trace3 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | LitellmModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | MessageBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def11 = string | null;
export type ShowResult11 = boolean;
export type Parser11 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback11 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role11 = string | null;
export type HasError11 = boolean;
export type Kind11 = "if";
export type Then =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Else =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type IfResult = boolean | null;
export type Def12 = string | null;
export type ShowResult12 = boolean;
export type Parser12 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback12 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role12 = string | null;
export type HasError12 = boolean;
export type Kind12 = "data";
export type Def13 = string | null;
export type ShowResult13 = boolean;
export type Parser13 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback13 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role13 = string | null;
export type HasError13 = boolean;
export type Kind13 = "get";
export type Get = string;
export type Def14 = string | null;
export type ShowResult14 = boolean;
export type Parser14 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback14 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role14 = string | null;
export type HasError14 = boolean;
export type Kind14 = "api";
export type Api = string;
export type Url = string;
export type Input =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def15 = string | null;
export type ShowResult15 = boolean;
export type Parser15 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback15 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role15 = string | null;
export type HasError15 = boolean;
export type Kind15 = "code";
export type Lan = "python";
export type Code =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def16 = string | null;
export type ShowResult16 = boolean;
export type Parser16 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback16 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role16 = string | null;
export type HasError16 = boolean;
export type Kind16 = "model";
export type Model = string;
export type Input1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Trace4 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Platform = "litellm";
export type Timeout = number | string | null;
export type Temperature = number | null;
export type TopP = number | null;
export type N = number | null;
export type Stop = string | string[] | null;
export type MaxTokens = number | null;
export type PresencePenalty = number | null;
export type FrequencyPenalty = number | null;
export type LogitBias = {
  [k: string]: unknown;
} | null;
export type User = string | null;
export type ResponseFormat = {
  [k: string]: unknown;
} | null;
export type Seed = number | null;
export type Tools = unknown[] | null;
export type ToolChoice =
  | string
  | {
      [k: string]: unknown;
    }
  | null;
export type Logprobs = boolean | null;
export type TopLogprobs = number | null;
export type ParallelToolCalls = boolean | null;
export type ExtraHeaders = {
  [k: string]: unknown;
} | null;
export type Functions = unknown[] | null;
export type FunctionCall = string | null;
export type BaseUrl = string | null;
export type ApiVersion = string | null;
export type ApiKey = string | null;
export type ModelList = unknown[] | null;
export type MockResponse = string | null;
export type CustomLlmProvider = string | null;
export type MaxRetries = number | null;
export type Def17 = string | null;
export type ShowResult17 = boolean;
export type Parser17 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback17 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role17 = string | null;
export type HasError17 = boolean;
export type Kind17 = "model";
export type Model1 = string;
export type Input2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Trace5 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Platform1 = "bam";
export type PromptId = string | null;
export type Parameters =
  | BamTextGenerationParameters
  | {
      [k: string]: unknown;
    }
  | null;
export type BeamWidth = number | null;
export type DecodingMethod = "greedy" | "sample";
export type IncludeStopSequence = boolean | null;
export type DecayFactor = number | null;
export type StartIndex = number | null;
export type MaxNewTokens = number | null;
export type MinNewTokens = number | null;
export type RandomSeed = number | null;
export type RepetitionPenalty = number | null;
export type GeneratedTokens = boolean | null;
export type InputParameters = boolean | null;
export type InputText = boolean | null;
export type InputTokens = boolean | null;
export type TokenLogprobs = boolean | null;
export type TokenRanks = boolean | null;
export type TopNTokens = number | null;
export type StopSequences =
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | null;
export type Temperature1 = number | null;
export type TimeLimit = number | null;
export type TopK = number | null;
export type TopPNucleusSampling = number | null;
export type TruncateInputTokens = number | null;
export type TypicalP = number | null;
export type Enabled = boolean | null;
export type SendTokens = boolean | null;
export type Threshold = number | null;
export type Enabled1 = boolean | null;
export type SendTokens1 = boolean | null;
export type Threshold1 = number | null;
export type Enabled2 = boolean | null;
export type SendTokens2 = boolean | null;
export type Threshold2 = number | null;
export type Enabled3 = boolean | null;
export type SendTokens3 = boolean | null;
export type Threshold3 = number | null;
export type ExampleFileIds =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | null;
export type Def18 = string | null;
export type ShowResult18 = boolean;
export type Parser18 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback18 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role18 = string | null;
export type HasError18 = boolean;
export type Kind18 = "model";
export type Model2 = string;
export type Input3 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Trace6 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Platform2 = "watsonx";
export type Params = {
  [k: string]: unknown;
} | null;
export type Guardrails = boolean | null;
export type GuardrailsHapParams = {
  [k: string]: unknown;
} | null;
export type Def19 = string | null;
export type ShowResult19 = boolean;
export type Parser19 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback19 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role19 = string | null;
export type HasError19 = boolean;
export type Kind19 = "call";
export type Call = string;
export type Trace7 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Def20 = string | null;
export type ShowResult20 = boolean;
export type Parser20 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Fallback20 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Role20 = string | null;
export type HasError20 = boolean;
export type Kind20 = "function";
export type Function = {
  [k: string]: unknown;
} | null;
export type Return =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Scope = {
  [k: string]: unknown;
} | null;
export type PdlBlock =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock;
export type PdlBlocks =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | LitellmModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | MessageBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | LitellmModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | MessageBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];

/**
 * Function declaration.
 */
export interface FunctionBlock {
  description?: Description;
  spec?: Spec;
  defs?: Defs;
  def?: Def20;
  show_result?: ShowResult20;
  parser?: Parser20;
  fallback?: Fallback20;
  role?: Role20;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError20;
  kind?: Kind20;
  function: Function;
  return: Return;
  scope?: Scope;
}
export interface Spec {
  [k: string]: unknown;
}
export interface Defs {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Calling a function.
 */
export interface CallBlock {
  description?: Description1;
  spec?: Spec1;
  defs?: Defs1;
  def?: Def19;
  show_result?: ShowResult19;
  parser?: Parser19;
  fallback?: Fallback19;
  role?: Role19;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError19;
  kind?: Kind19;
  call: Call;
  args?: Args;
  trace?: Trace7;
}
export interface Spec1 {
  [k: string]: unknown;
}
export interface Defs1 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Call a LLM through the watsonx.ai API: https://ibm.github.io/watsonx-ai-python-sdk.
 */
export interface WatsonxModelBlock {
  description?: Description2;
  spec?: Spec2;
  defs?: Defs2;
  def?: Def18;
  show_result?: ShowResult18;
  parser?: Parser18;
  fallback?: Fallback18;
  role?: Role18;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError18;
  kind?: Kind18;
  model: Model2;
  input?: Input3;
  trace?: Trace6;
  platform?: Platform2;
  params?: Params;
  guardrails?: Guardrails;
  guardrails_hap_params?: GuardrailsHapParams;
}
export interface Spec2 {
  [k: string]: unknown;
}
export interface Defs2 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface BamModelBlock {
  description?: Description3;
  spec?: Spec3;
  defs?: Defs3;
  def?: Def17;
  show_result?: ShowResult17;
  parser?: Parser17;
  fallback?: Fallback17;
  role?: Role17;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError17;
  kind?: Kind17;
  model: Model1;
  input?: Input2;
  trace?: Trace5;
  platform?: Platform1;
  prompt_id?: PromptId;
  parameters?: Parameters;
  moderations?: ModerationParameters | null;
  data?: PromptTemplateData | null;
  constraints?: Constraints;
}
export interface Spec3 {
  [k: string]: unknown;
}
export interface Defs3 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Call a LLM through the LiteLLM API: https://docs.litellm.ai/.
 */
export interface LitellmModelBlock {
  description?: Description4;
  spec?: Spec4;
  defs?: Defs4;
  def?: Def16;
  show_result?: ShowResult16;
  parser?: Parser16;
  fallback?: Fallback16;
  role?: Role16;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError16;
  kind?: Kind16;
  model: Model;
  input?: Input1;
  trace?: Trace4;
  platform?: Platform;
  parameters?: LitellmParameters | null;
}
export interface Spec4 {
  [k: string]: unknown;
}
export interface Defs4 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Execute a piece of code.
 */
export interface CodeBlock {
  description?: Description5;
  spec?: Spec5;
  defs?: Defs5;
  def?: Def15;
  show_result?: ShowResult15;
  parser?: Parser15;
  fallback?: Fallback15;
  role?: Role15;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError15;
  kind?: Kind15;
  lan: Lan;
  code: Code;
}
export interface Spec5 {
  [k: string]: unknown;
}
export interface Defs5 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Call an API.
 */
export interface ApiBlock {
  description?: Description6;
  spec?: Spec6;
  defs?: Defs6;
  def?: Def14;
  show_result?: ShowResult14;
  parser?: Parser14;
  fallback?: Fallback14;
  role?: Role14;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError14;
  kind?: Kind14;
  api: Api;
  url: Url;
  input: Input;
}
export interface Spec6 {
  [k: string]: unknown;
}
export interface Defs6 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Get the value of a variable.
 */
export interface GetBlock {
  description?: Description7;
  spec?: Spec7;
  defs?: Defs7;
  def?: Def13;
  show_result?: ShowResult13;
  parser?: Parser13;
  fallback?: Fallback13;
  role?: Role13;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError13;
  kind?: Kind13;
  get: Get;
}
export interface Spec7 {
  [k: string]: unknown;
}
export interface Defs7 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Arbitrary JSON value.
 */
export interface DataBlock {
  description?: Description8;
  spec?: Spec8;
  defs?: Defs8;
  def?: Def12;
  show_result?: ShowResult12;
  parser?: Parser12;
  fallback?: Fallback12;
  role?: Role12;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError12;
  kind?: Kind12;
  data: Data;
}
export interface Spec8 {
  [k: string]: unknown;
}
export interface Defs8 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Conditional control structure.
 */
export interface IfBlock {
  description?: Description9;
  spec?: Spec9;
  defs?: Defs9;
  def?: Def11;
  show_result?: ShowResult11;
  parser?: Parser11;
  fallback?: Fallback11;
  role?: Role11;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError11;
  kind?: Kind11;
  if: If;
  then: Then;
  else?: Else;
  if_result?: IfResult;
}
export interface Spec9 {
  [k: string]: unknown;
}
export interface Defs9 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Repeat the execution of a block for a fixed number of iterations.
 */
export interface RepeatBlock {
  description?: Description10;
  spec?: Spec10;
  defs?: Defs10;
  def?: Def10;
  show_result?: ShowResult10;
  parser?: Parser10;
  fallback?: Fallback10;
  role?: Role10;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError10;
  kind?: Kind10;
  repeat: Repeat2;
  num_iterations: NumIterations;
  as?: IterationType & string;
  trace?: Trace3;
}
export interface Spec10 {
  [k: string]: unknown;
}
export interface Defs10 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Repeat the execution of a block until a condition is satisfied.
 */
export interface RepeatUntilBlock {
  description?: Description11;
  spec?: Spec11;
  defs?: Defs11;
  def?: Def9;
  show_result?: ShowResult9;
  parser?: Parser9;
  fallback?: Fallback9;
  role?: Role9;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError9;
  kind?: Kind9;
  repeat: Repeat1;
  until: Until;
  as?: IterationType & string;
  trace?: Trace2;
}
export interface Spec11 {
  [k: string]: unknown;
}
export interface Defs11 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Iteration over arrays.
 */
export interface ForBlock {
  description?: Description12;
  spec?: Spec12;
  defs?: Defs12;
  def?: Def8;
  show_result?: ShowResult8;
  parser?: Parser8;
  fallback?: Fallback8;
  role?: Role8;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError8;
  kind?: Kind8;
  for: For;
  repeat: Repeat;
  as?: IterationType & string;
  trace?: Trace1;
}
export interface Spec12 {
  [k: string]: unknown;
}
export interface Defs12 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Create the concatenation of the stringify version of the result of each block of the list of blocks.
 */
export interface DocumentBlock {
  description?: Description13;
  spec?: Spec13;
  defs?: Defs13;
  def?: Def7;
  show_result?: ShowResult7;
  parser?: Parser7;
  fallback?: Fallback7;
  role?: Role7;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError7;
  kind?: Kind7;
  document: Document;
}
export interface Spec13 {
  [k: string]: unknown;
}
export interface Defs13 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Return the value of the last block if the list of blocks.
 */
export interface SequenceBlock {
  description?: Description14;
  spec?: Spec14;
  defs?: Defs14;
  def?: Def6;
  show_result?: ShowResult6;
  parser?: Parser6;
  fallback?: Fallback6;
  role?: Role6;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError6;
  kind?: Kind6;
  sequence: Sequence;
}
export interface Spec14 {
  [k: string]: unknown;
}
export interface Defs14 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Return the array of values computed by each block of the list of blocks.
 */
export interface ArrayBlock {
  description?: Description15;
  spec?: Spec15;
  defs?: Defs15;
  def?: Def5;
  show_result?: ShowResult5;
  parser?: Parser5;
  fallback?: Fallback5;
  role?: Role5;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError5;
  kind?: Kind5;
  array: Array;
}
export interface Spec15 {
  [k: string]: unknown;
}
export interface Defs15 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Create a message.
 */
export interface MessageBlock {
  description?: Description16;
  spec?: Spec16;
  defs?: Defs16;
  def?: Def4;
  show_result?: ShowResult4;
  parser?: Parser4;
  fallback?: Fallback4;
  role: Role4;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError4;
  kind?: Kind4;
  content: Content;
}
export interface Spec16 {
  [k: string]: unknown;
}
export interface Defs16 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Read from a file or standard input.
 */
export interface ReadBlock {
  description?: Description17;
  spec?: Spec17;
  defs?: Defs17;
  def?: Def3;
  show_result?: ShowResult3;
  parser?: Parser3;
  fallback?: Fallback3;
  role?: Role3;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError3;
  kind?: Kind3;
  read: Read;
  message?: Message;
  multiline?: Multiline;
}
export interface Spec17 {
  [k: string]: unknown;
}
export interface Defs17 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Include a PDL file.
 */
export interface IncludeBlock {
  description?: Description18;
  spec?: Spec18;
  defs?: Defs18;
  def?: Def2;
  show_result?: ShowResult2;
  parser?: Parser2;
  fallback?: Fallback2;
  role?: Role2;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError2;
  kind?: Kind2;
  include: Include;
  trace?: Trace;
}
export interface Spec18 {
  [k: string]: unknown;
}
export interface Defs18 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ErrorBlock {
  description?: Description19;
  spec?: Spec19;
  defs?: Defs19;
  def?: Def1;
  show_result?: ShowResult1;
  parser?: Parser1;
  fallback?: Fallback1;
  role?: Role1;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError1;
  kind?: Kind1;
  msg: Msg;
  program: Program1;
}
export interface Spec19 {
  [k: string]: unknown;
}
export interface Defs19 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
/**
 * Block without an action. It can contain definitions.
 */
export interface EmptyBlock {
  description?: Description20;
  spec?: Spec20;
  defs?: Defs20;
  def?: Def;
  show_result?: ShowResult;
  parser?: Parser;
  fallback?: Fallback;
  role?: Role;
  result?: unknown;
  location?: LocationType | null;
  has_error?: HasError;
  kind?: Kind;
}
export interface Spec20 {
  [k: string]: unknown;
}
export interface Defs20 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | LitellmModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | MessageBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | LitellmModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | MessageBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface PdlParser {
  description?: Description21;
  spec?: Spec21;
  pdl: Pdl;
}
export interface RegexParser {
  description?: Description22;
  spec?: Spec22;
  regex: Regex;
  mode?: Mode;
}
export interface LocationType {
  path: Path;
  file: File;
  table: Table;
}
export interface Table {
  [k: string]: number;
}
export interface For {
  [k: string]: unknown;
}
export interface Until {
  [k: string]: unknown;
}
export interface If {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
/**
 * Parameters passed to LiteLLM. More details at https://docs.litellm.ai/docs/completion/input.
 */
export interface LitellmParameters {
  timeout?: Timeout;
  temperature?: Temperature;
  top_p?: TopP;
  n?: N;
  stop?: Stop;
  max_tokens?: MaxTokens;
  presence_penalty?: PresencePenalty;
  frequency_penalty?: FrequencyPenalty;
  logit_bias?: LogitBias;
  user?: User;
  response_format?: ResponseFormat;
  seed?: Seed;
  tools?: Tools;
  tool_choice?: ToolChoice;
  logprobs?: Logprobs;
  top_logprobs?: TopLogprobs;
  parallel_tool_calls?: ParallelToolCalls;
  extra_headers?: ExtraHeaders;
  functions?: Functions;
  function_call?: FunctionCall;
  base_url?: BaseUrl;
  api_version?: ApiVersion;
  api_key?: ApiKey;
  model_list?: ModelList;
  mock_response?: MockResponse;
  custom_llm_provider?: CustomLlmProvider;
  max_retries?: MaxRetries;
  [k: string]: unknown;
}
export interface BamTextGenerationParameters {
  beam_width?: BeamWidth;
  decoding_method?: DecodingMethod | null;
  include_stop_sequence?: IncludeStopSequence;
  length_penalty?: LengthPenalty | null;
  max_new_tokens?: MaxNewTokens;
  min_new_tokens?: MinNewTokens;
  random_seed?: RandomSeed;
  repetition_penalty?: RepetitionPenalty;
  return_options?: TextGenerationReturnOptions | null;
  stop_sequences?: StopSequences;
  temperature?: Temperature1;
  time_limit?: TimeLimit;
  top_k?: TopK;
  top_p?: TopPNucleusSampling;
  truncate_input_tokens?: TruncateInputTokens;
  typical_p?: TypicalP;
}
export interface LengthPenalty {
  decay_factor?: DecayFactor;
  start_index?: StartIndex;
  [k: string]: unknown;
}
export interface TextGenerationReturnOptions {
  generated_tokens?: GeneratedTokens;
  input_parameters?: InputParameters;
  input_text?: InputText;
  input_tokens?: InputTokens;
  token_logprobs?: TokenLogprobs;
  token_ranks?: TokenRanks;
  top_n_tokens?: TopNTokens;
  [k: string]: unknown;
}
export interface ModerationParameters {
  hap?: ModerationHAP | null;
  social_bias?: ModerationSocialBias | null;
  [k: string]: unknown;
}
export interface ModerationHAP {
  input?: ModerationHAPInput | null;
  output?: ModerationHAPOutput | null;
  [k: string]: unknown;
}
export interface ModerationHAPInput {
  enabled?: Enabled;
  send_tokens?: SendTokens;
  threshold?: Threshold;
  [k: string]: unknown;
}
export interface ModerationHAPOutput {
  enabled?: Enabled1;
  send_tokens?: SendTokens1;
  threshold?: Threshold1;
  [k: string]: unknown;
}
export interface ModerationSocialBias {
  input?: ModerationSocialBiasInput | null;
  output?: ModerationSocialBiasOutput | null;
  [k: string]: unknown;
}
export interface ModerationSocialBiasInput {
  enabled?: Enabled2;
  send_tokens?: SendTokens2;
  threshold?: Threshold2;
  [k: string]: unknown;
}
export interface ModerationSocialBiasOutput {
  enabled?: Enabled3;
  send_tokens?: SendTokens3;
  threshold?: Threshold3;
  [k: string]: unknown;
}
export interface PromptTemplateData {
  example_file_ids?: ExampleFileIds;
  [k: string]: unknown;
}
export interface Constraints {
  [k: string]: unknown;
}
export interface Args {
  [k: string]: unknown;
}
