/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PDLSchemas = Program | PdlBlock | PdlBlocks;
/**
 * Prompt Description Program (PDL)
 */
export type Program =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock;
export type Description = string | null;
export type Description1 = string | null;
export type Description2 = string | null;
export type Description3 = string | null;
export type Description4 = string | null;
export type Description5 = string | null;
export type Description6 = string | null;
export type Description7 = string | null;
export type Description8 = string | null;
export type Description9 = string | null;
export type Description10 = string | null;
export type Description11 = string | null;
export type Description12 = string | null;
export type Description13 = string | null;
export type Description14 = string | null;
export type Description15 = string | null;
export type Description16 = string | null;
export type Description17 = string | null;
export type Description18 = string | null;
export type Def = string | null;
export type ShowResult = boolean;
export type Parser = ("json" | "yaml") | PdlParser | RegexParser | null;
export type Description19 = string | null;
export type Spec19 = {
  [k: string]: unknown;
} | null;
export type Pdl =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Description20 = string | null;
export type Spec20 = {
  [k: string]: unknown;
} | null;
export type Regex = string;
export type Mode = "search" | "match" | "fullmatch" | "split" | "findall";
export type Path = string[];
export type File = string;
export type HasError = boolean;
export type Fallback =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind = "empty";
export type Def1 = string | null;
export type ShowResult1 = boolean;
export type Parser1 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError1 = boolean;
export type Fallback1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind1 = "error";
export type Msg = string;
export type Program1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def2 = string | null;
export type ShowResult2 = boolean;
export type Parser2 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError2 = boolean;
export type Fallback2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind2 = "include";
export type Include = string;
export type Trace =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Def3 = string | null;
export type ShowResult3 = boolean;
export type Parser3 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError3 = boolean;
export type Fallback3 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind3 = "read";
export type Read = string | null;
export type Message = string | null;
export type Multiline = boolean;
export type Def4 = string | null;
export type ShowResult4 = boolean;
export type Parser4 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError4 = boolean;
export type Fallback4 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind4 = "array";
export type Array =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def5 = string | null;
export type ShowResult5 = boolean;
export type Parser5 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError5 = boolean;
export type Fallback5 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind5 = "sequence";
export type Sequence =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def6 = string | null;
export type ShowResult6 = boolean;
export type Parser6 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError6 = boolean;
export type Fallback6 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind6 = "document";
export type Document =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def7 = string | null;
export type ShowResult7 = boolean;
export type Parser7 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError7 = boolean;
export type Fallback7 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind7 = "for";
export type Repeat =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type IterationType = "sequence" | "array" | "document";
export type Trace1 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def8 = string | null;
export type ShowResult8 = boolean;
export type Parser8 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError8 = boolean;
export type Fallback8 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind8 = "repeat_until";
export type Repeat1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Trace2 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def9 = string | null;
export type ShowResult9 = boolean;
export type Parser9 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError9 = boolean;
export type Fallback9 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind9 = "repeat";
export type Repeat2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type NumIterations = number;
export type Trace3 =
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
      | (
          | number
          | number
          | string
          | FunctionBlock
          | CallBlock
          | WatsonxModelBlock
          | BamModelBlock
          | CodeBlock
          | ApiBlock
          | GetBlock
          | DataBlock
          | IfBlock
          | RepeatBlock
          | RepeatUntilBlock
          | ForBlock
          | DocumentBlock
          | SequenceBlock
          | ArrayBlock
          | ReadBlock
          | IncludeBlock
          | ErrorBlock
          | EmptyBlock
        )[]
    )[]
  | null;
export type Def10 = string | null;
export type ShowResult10 = boolean;
export type Parser10 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError10 = boolean;
export type Fallback10 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind10 = "if";
export type Then =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Else =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type IfResult = boolean | null;
export type Def11 = string | null;
export type ShowResult11 = boolean;
export type Parser11 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError11 = boolean;
export type Fallback11 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind11 = "data";
export type Def12 = string | null;
export type ShowResult12 = boolean;
export type Parser12 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError12 = boolean;
export type Fallback12 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind12 = "get";
export type Get = string;
export type Def13 = string | null;
export type ShowResult13 = boolean;
export type Parser13 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError13 = boolean;
export type Fallback13 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind13 = "api";
export type Api = string;
export type Url = string;
export type Input =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def14 = string | null;
export type ShowResult14 = boolean;
export type Parser14 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError14 = boolean;
export type Fallback14 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind14 = "code";
export type Lan = "python";
export type Code =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Def15 = string | null;
export type ShowResult15 = boolean;
export type Parser15 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError15 = boolean;
export type Fallback15 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind15 = "model";
export type Model = string;
export type Input1 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Trace4 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Platform = "bam";
export type PromptId = string | null;
export type Parameters = {
  [k: string]: unknown;
} | null;
export type Enabled = boolean | null;
export type SendTokens = boolean | null;
export type Threshold = number | null;
export type Enabled1 = boolean | null;
export type SendTokens1 = boolean | null;
export type Threshold1 = number | null;
export type Enabled2 = boolean | null;
export type SendTokens2 = boolean | null;
export type Threshold2 = number | null;
export type Enabled3 = boolean | null;
export type SendTokens3 = boolean | null;
export type Threshold3 = number | null;
export type ExampleFileIds =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | null;
export type Def16 = string | null;
export type ShowResult16 = boolean;
export type Parser16 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError16 = boolean;
export type Fallback16 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind16 = "model";
export type Model1 = string;
export type Input2 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Trace5 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | null;
export type Platform1 = "watsonx";
export type Params = {
  [k: string]: unknown;
} | null;
export type Guardrails = boolean | null;
export type GuardrailsHapParams = {
  [k: string]: unknown;
} | null;
export type Def17 = string | null;
export type ShowResult17 = boolean;
export type Parser17 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError17 = boolean;
export type Fallback17 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind17 = "call";
export type Call = string;
export type Trace6 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Def18 = string | null;
export type ShowResult18 = boolean;
export type Parser18 = ("json" | "yaml") | PdlParser | RegexParser | null;
export type HasError18 = boolean;
export type Fallback18 =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[]
  | null;
export type Kind18 = "function";
export type Function = {
  [k: string]: unknown;
} | null;
export type Return =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];
export type Scope = {
  [k: string]: unknown;
} | null;
export type PdlBlock =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock;
export type PdlBlocks =
  | number
  | string
  | FunctionBlock
  | CallBlock
  | WatsonxModelBlock
  | BamModelBlock
  | CodeBlock
  | ApiBlock
  | GetBlock
  | DataBlock
  | IfBlock
  | RepeatBlock
  | RepeatUntilBlock
  | ForBlock
  | DocumentBlock
  | SequenceBlock
  | ArrayBlock
  | ReadBlock
  | IncludeBlock
  | ErrorBlock
  | EmptyBlock
  | (
      | number
      | number
      | string
      | FunctionBlock
      | CallBlock
      | WatsonxModelBlock
      | BamModelBlock
      | CodeBlock
      | ApiBlock
      | GetBlock
      | DataBlock
      | IfBlock
      | RepeatBlock
      | RepeatUntilBlock
      | ForBlock
      | DocumentBlock
      | SequenceBlock
      | ArrayBlock
      | ReadBlock
      | IncludeBlock
      | ErrorBlock
      | EmptyBlock
    )[];

export interface FunctionBlock {
  description?: Description;
  spec?: Spec;
  defs?: Defs;
  def?: Def18;
  show_result?: ShowResult18;
  result?: unknown;
  parser?: Parser18;
  location?: LocationType | null;
  has_error?: HasError18;
  fallback?: Fallback18;
  kind?: Kind18;
  function: Function;
  return: Return;
  scope?: Scope;
}
export interface Spec {
  [k: string]: unknown;
}
export interface Defs {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface CallBlock {
  description?: Description1;
  spec?: Spec1;
  defs?: Defs1;
  def?: Def17;
  show_result?: ShowResult17;
  result?: unknown;
  parser?: Parser17;
  location?: LocationType | null;
  has_error?: HasError17;
  fallback?: Fallback17;
  kind?: Kind17;
  call: Call;
  args?: Args;
  trace?: Trace6;
}
export interface Spec1 {
  [k: string]: unknown;
}
export interface Defs1 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface WatsonxModelBlock {
  description?: Description2;
  spec?: Spec2;
  defs?: Defs2;
  def?: Def16;
  show_result?: ShowResult16;
  result?: unknown;
  parser?: Parser16;
  location?: LocationType | null;
  has_error?: HasError16;
  fallback?: Fallback16;
  kind?: Kind16;
  model: Model1;
  input?: Input2;
  trace?: Trace5;
  platform?: Platform1;
  params?: Params;
  guardrails?: Guardrails;
  guardrails_hap_params?: GuardrailsHapParams;
}
export interface Spec2 {
  [k: string]: unknown;
}
export interface Defs2 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface BamModelBlock {
  description?: Description3;
  spec?: Spec3;
  defs?: Defs3;
  def?: Def15;
  show_result?: ShowResult15;
  result?: unknown;
  parser?: Parser15;
  location?: LocationType | null;
  has_error?: HasError15;
  fallback?: Fallback15;
  kind?: Kind15;
  model: Model;
  input?: Input1;
  trace?: Trace4;
  platform?: Platform;
  prompt_id?: PromptId;
  parameters?: Parameters;
  moderations?: ModerationParameters | null;
  data?: PromptTemplateData | null;
  constraints?: Constraints;
}
export interface Spec3 {
  [k: string]: unknown;
}
export interface Defs3 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface CodeBlock {
  description?: Description4;
  spec?: Spec4;
  defs?: Defs4;
  def?: Def14;
  show_result?: ShowResult14;
  result?: unknown;
  parser?: Parser14;
  location?: LocationType | null;
  has_error?: HasError14;
  fallback?: Fallback14;
  kind?: Kind14;
  lan: Lan;
  code: Code;
}
export interface Spec4 {
  [k: string]: unknown;
}
export interface Defs4 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ApiBlock {
  description?: Description5;
  spec?: Spec5;
  defs?: Defs5;
  def?: Def13;
  show_result?: ShowResult13;
  result?: unknown;
  parser?: Parser13;
  location?: LocationType | null;
  has_error?: HasError13;
  fallback?: Fallback13;
  kind?: Kind13;
  api: Api;
  url: Url;
  input: Input;
}
export interface Spec5 {
  [k: string]: unknown;
}
export interface Defs5 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface GetBlock {
  description?: Description6;
  spec?: Spec6;
  defs?: Defs6;
  def?: Def12;
  show_result?: ShowResult12;
  result?: unknown;
  parser?: Parser12;
  location?: LocationType | null;
  has_error?: HasError12;
  fallback?: Fallback12;
  kind?: Kind12;
  get: Get;
}
export interface Spec6 {
  [k: string]: unknown;
}
export interface Defs6 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface DataBlock {
  description?: Description7;
  spec?: Spec7;
  defs?: Defs7;
  def?: Def11;
  show_result?: ShowResult11;
  result?: unknown;
  parser?: Parser11;
  location?: LocationType | null;
  has_error?: HasError11;
  fallback?: Fallback11;
  kind?: Kind11;
  data: Data;
}
export interface Spec7 {
  [k: string]: unknown;
}
export interface Defs7 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface IfBlock {
  description?: Description8;
  spec?: Spec8;
  defs?: Defs8;
  def?: Def10;
  show_result?: ShowResult10;
  result?: unknown;
  parser?: Parser10;
  location?: LocationType | null;
  has_error?: HasError10;
  fallback?: Fallback10;
  kind?: Kind10;
  if: If;
  then: Then;
  else?: Else;
  if_result?: IfResult;
}
export interface Spec8 {
  [k: string]: unknown;
}
export interface Defs8 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface RepeatBlock {
  description?: Description9;
  spec?: Spec9;
  defs?: Defs9;
  def?: Def9;
  show_result?: ShowResult9;
  result?: unknown;
  parser?: Parser9;
  location?: LocationType | null;
  has_error?: HasError9;
  fallback?: Fallback9;
  kind?: Kind9;
  repeat: Repeat2;
  num_iterations: NumIterations;
  as?: IterationType & string;
  trace?: Trace3;
}
export interface Spec9 {
  [k: string]: unknown;
}
export interface Defs9 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface RepeatUntilBlock {
  description?: Description10;
  spec?: Spec10;
  defs?: Defs10;
  def?: Def8;
  show_result?: ShowResult8;
  result?: unknown;
  parser?: Parser8;
  location?: LocationType | null;
  has_error?: HasError8;
  fallback?: Fallback8;
  kind?: Kind8;
  repeat: Repeat1;
  until: Until;
  as?: IterationType & string;
  trace?: Trace2;
}
export interface Spec10 {
  [k: string]: unknown;
}
export interface Defs10 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ForBlock {
  description?: Description11;
  spec?: Spec11;
  defs?: Defs11;
  def?: Def7;
  show_result?: ShowResult7;
  result?: unknown;
  parser?: Parser7;
  location?: LocationType | null;
  has_error?: HasError7;
  fallback?: Fallback7;
  kind?: Kind7;
  for: For;
  repeat: Repeat;
  as?: IterationType & string;
  trace?: Trace1;
}
export interface Spec11 {
  [k: string]: unknown;
}
export interface Defs11 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface DocumentBlock {
  description?: Description12;
  spec?: Spec12;
  defs?: Defs12;
  def?: Def6;
  show_result?: ShowResult6;
  result?: unknown;
  parser?: Parser6;
  location?: LocationType | null;
  has_error?: HasError6;
  fallback?: Fallback6;
  kind?: Kind6;
  document: Document;
}
export interface Spec12 {
  [k: string]: unknown;
}
export interface Defs12 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface SequenceBlock {
  description?: Description13;
  spec?: Spec13;
  defs?: Defs13;
  def?: Def5;
  show_result?: ShowResult5;
  result?: unknown;
  parser?: Parser5;
  location?: LocationType | null;
  has_error?: HasError5;
  fallback?: Fallback5;
  kind?: Kind5;
  sequence: Sequence;
}
export interface Spec13 {
  [k: string]: unknown;
}
export interface Defs13 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ArrayBlock {
  description?: Description14;
  spec?: Spec14;
  defs?: Defs14;
  def?: Def4;
  show_result?: ShowResult4;
  result?: unknown;
  parser?: Parser4;
  location?: LocationType | null;
  has_error?: HasError4;
  fallback?: Fallback4;
  kind?: Kind4;
  array: Array;
}
export interface Spec14 {
  [k: string]: unknown;
}
export interface Defs14 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ReadBlock {
  description?: Description15;
  spec?: Spec15;
  defs?: Defs15;
  def?: Def3;
  show_result?: ShowResult3;
  result?: unknown;
  parser?: Parser3;
  location?: LocationType | null;
  has_error?: HasError3;
  fallback?: Fallback3;
  kind?: Kind3;
  read: Read;
  message?: Message;
  multiline?: Multiline;
}
export interface Spec15 {
  [k: string]: unknown;
}
export interface Defs15 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface IncludeBlock {
  description?: Description16;
  spec?: Spec16;
  defs?: Defs16;
  def?: Def2;
  show_result?: ShowResult2;
  result?: unknown;
  parser?: Parser2;
  location?: LocationType | null;
  has_error?: HasError2;
  fallback?: Fallback2;
  kind?: Kind2;
  include: Include;
  trace?: Trace;
}
export interface Spec16 {
  [k: string]: unknown;
}
export interface Defs16 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface ErrorBlock {
  description?: Description17;
  spec?: Spec17;
  defs?: Defs17;
  def?: Def1;
  show_result?: ShowResult1;
  result?: unknown;
  parser?: Parser1;
  location?: LocationType | null;
  has_error?: HasError1;
  fallback?: Fallback1;
  kind?: Kind1;
  msg: Msg;
  program: Program1;
}
export interface Spec17 {
  [k: string]: unknown;
}
export interface Defs17 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface EmptyBlock {
  description?: Description18;
  spec?: Spec18;
  defs?: Defs18;
  def?: Def;
  show_result?: ShowResult;
  result?: unknown;
  parser?: Parser;
  location?: LocationType | null;
  has_error?: HasError;
  fallback?: Fallback;
  kind?: Kind;
}
export interface Spec18 {
  [k: string]: unknown;
}
export interface Defs18 {
  [k: string]:
    | number
    | string
    | FunctionBlock
    | CallBlock
    | WatsonxModelBlock
    | BamModelBlock
    | CodeBlock
    | ApiBlock
    | GetBlock
    | DataBlock
    | IfBlock
    | RepeatBlock
    | RepeatUntilBlock
    | ForBlock
    | DocumentBlock
    | SequenceBlock
    | ArrayBlock
    | ReadBlock
    | IncludeBlock
    | ErrorBlock
    | EmptyBlock
    | (
        | number
        | number
        | string
        | FunctionBlock
        | CallBlock
        | WatsonxModelBlock
        | BamModelBlock
        | CodeBlock
        | ApiBlock
        | GetBlock
        | DataBlock
        | IfBlock
        | RepeatBlock
        | RepeatUntilBlock
        | ForBlock
        | DocumentBlock
        | SequenceBlock
        | ArrayBlock
        | ReadBlock
        | IncludeBlock
        | ErrorBlock
        | EmptyBlock
      )[];
}
export interface PdlParser {
  description?: Description19;
  spec?: Spec19;
  pdl: Pdl;
}
export interface RegexParser {
  description?: Description20;
  spec?: Spec20;
  regex: Regex;
  mode?: Mode;
}
export interface LocationType {
  path: Path;
  file: File;
  table: Table;
}
export interface Table {
  [k: string]: number;
}
export interface For {
  [k: string]: unknown;
}
export interface Until {
  [k: string]: unknown;
}
export interface If {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
export interface ModerationParameters {
  hap?: ModerationHAP | null;
  social_bias?: ModerationSocialBias | null;
  [k: string]: unknown;
}
export interface ModerationHAP {
  input?: ModerationHAPInput | null;
  output?: ModerationHAPOutput | null;
  [k: string]: unknown;
}
export interface ModerationHAPInput {
  enabled?: Enabled;
  send_tokens?: SendTokens;
  threshold?: Threshold;
  [k: string]: unknown;
}
export interface ModerationHAPOutput {
  enabled?: Enabled1;
  send_tokens?: SendTokens1;
  threshold?: Threshold1;
  [k: string]: unknown;
}
export interface ModerationSocialBias {
  input?: ModerationSocialBiasInput | null;
  output?: ModerationSocialBiasOutput | null;
  [k: string]: unknown;
}
export interface ModerationSocialBiasInput {
  enabled?: Enabled2;
  send_tokens?: SendTokens2;
  threshold?: Threshold2;
  [k: string]: unknown;
}
export interface ModerationSocialBiasOutput {
  enabled?: Enabled3;
  send_tokens?: SendTokens3;
  threshold?: Threshold3;
  [k: string]: unknown;
}
export interface PromptTemplateData {
  example_file_ids?: ExampleFileIds;
  [k: string]: unknown;
}
export interface Constraints {
  [k: string]: unknown;
}
export interface Args {
  [k: string]: unknown;
}
