name: Viewer Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# cancel any prior runs for this workflow and this PR (or branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  viewer:
    name: Test PDL live viewer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pdl-live-react
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Linux dependencies
        # only if we ever add a drawer menu libappindicator3-dev
        # re: at-spi2-core, Warning **: Error retrieving accessibility bus address:
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf at-spi2-core
      - name: Install NodeJs dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Test pdl-live viewer
        run: npm test
      - name: Test production build
        run: npm run prod:linux
      - name: Setup xvfb for screen 0
        run: Xvfb :1 -screen 0 1600x1200x24 &      
      - name: Run production build
        env:
          DISPLAY: :1
        run: ./src-tauri/target/x86_64-unknown-linux-gnu/release/PDL notacommand || true
      - name: Tear down xvfb
        run: killall Xvfb  
